version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - global-net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - global-net

  service-template:
    build:
      context: ./shared/service-template
    command: python -m uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    volumes:
      - .:/workspace
    working_dir: /workspace
    networks:
      - global-net

volumes:
  pgdata:

networks:
  global-net: