# DigitalOcean App Platform Configuration
# Detecta automaticamente a estrutura do projeto
name: globalautomation-trading
region: nyc

# Backend API (FastAPI)
services:
  - name: trading-api
    type: web
    github:
      repo: Mvmmv86/GlobalAutomation
      branch: main
      deploy_on_push: true

    source_dir: apps/api-python

    build_command: pip install -r requirements.txt

    run_command: uvicorn main:app --host 0.0.0.0 --port 8000

    http_port: 8000

    instance_count: 1
    instance_size_slug: basic-xxs

    envs:
      - key: ENV
        value: production
      - key: DEBUG
        value: "false"
      - key: PORT
        value: "8000"
      # IMPORTANTE: Configure os secrets no painel do App Platform
      - key: SECRET_KEY
        type: SECRET
      - key: ENCRYPTION_KEY
        type: SECRET
      - key: DATABASE_URL
        type: SECRET
      - key: TV_WEBHOOK_SECRET
        type: SECRET
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: RATE_LIMIT_PER_MINUTE
        value: "100"
      - key: WEBHOOK_RATE_LIMIT_PER_MINUTE
        value: "200"
      - key: LOG_LEVEL
        value: INFO

    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

# Frontend (React + Vite)
static_sites:
  - name: trading-frontend
    github:
      repo: Mvmmv86/GlobalAutomation
      branch: main
      deploy_on_push: true

    source_dir: frontend-new

    build_command: npm install && npm run build

    output_dir: dist

    envs:
      - key: VITE_API_URL
        value: ${trading-api.PUBLIC_URL}/api/v1
      - key: VITE_NODE_ENV
        value: production
      - key: VITE_APP_NAME
        value: Trading Platform
      - key: VITE_APP_VERSION
        value: "1.0.0"

    routes:
      - path: /

# Domains (configure depois do deploy)
# domains:
#   - domain: app.seudominio.com
#     type: PRIMARY
#     zone: seudominio.com
